### config path
log_path: /home/xxx/log
config_path: /home/xxx/catkin_ctrlvio/src/Ctrl-VIO/config
imu_yaml: /tumrs/imu_tumrs.yaml
cam_yaml: /tumrs/cam_tumrs.yaml

### bag param
bag_path: /home/xxx/Dataset/TUM/dataset-seq1.bag
bag_start: 0
bag_durr: -1

### spline param
knot_distance: 0.05

### noise & weight
gyroscope_noise_density: 4.0e-3
gyroscope_random_walk: 2.0e-5
accelerometer_noise_density: 8.0e-2
accelerometer_random_walk: 4.0e-4
image_weight: 800.0

### cam2imu
CameraExtrinsics:
    time_offset: 0.000
    Trans: [0.00699407, -0.0570823, -0.0422772]
    Rot: [ -0.00276873, -0.999936, -0.0110011,
               -0.999987, 0.00281495, -0.00418819,
               0.00421888, 0.0109894, -0.999931]

### for line delay optimization
ld_init: 0.0  #0.0000294737
fix_ld: false  #true 
ld_lower: 0.0
ld_upper: 0.000035
