%YAML:1.0

### common parameters
image_topic: /cam1/image_raw

### camera calibration
model_type: KANNALA_BRANDT
camera_name: cam1
image_width: 1280
image_height: 1024
projection_parameters:
   k2: 0.019327620961435945
   k3: 0.006784242994724914
   k4: -0.008658628531456217
   k5: 0.0051893686731546585
   mu: 739.1654756101043
   mv: 739.1438452683457
   u0: 625.826167006398
   v0: 517.3370973594253
focal_length: 740

### feature traker paprameters
max_cnt: 150            # max feature number in feature tracking
min_dist: 25            # min distance between two features
freq: 10                 # frequence (Hz) of publish tracking result. At least 10Hz for good estimation. If set 0, the frequence will be same as raw image
F_threshold: 1.0        # ransac threshold (pixel)
show_track: 1           # publish tracking image as topic
equalize: 1             # if image is too dark or light, trun on equalize to find enough features
fisheye: 0              # if using fisheye, trun on it. A circle mask will be loaded to remove edge noisy points
flow_back: 1       # cross-checking to remove outliers
fb_threshold: 0.5  #cross-checking threshold
reject_wf: 0

### optimization parameters
keyframe_parallax: 10.0 # keyframe selection threshold (pixel)
